<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Please_provide_detail</name>
   <tag></tag>
   <elementGuidId>a6e2e64b-bc0d-47a7-b2fd-41bd4b8c77f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;id-form&quot;]/div[5]/div[1]/textarea</value>
   </webElementProperties>
</WebElementEntity>
