<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon_ca-icon__colored-strok</name>
   <tag></tag>
   <elementGuidId>0ebd5277-a113-4e4b-aec9-a817b818b887</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ca-icon__colored-stroke ca-icon__colored-fill</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>16.8945</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-miterlimit</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>50.05,699.89 71.22,742.26 118.25,749 84.49,781.81 92.49,828.78 50.44,806.99 7.81,828.96 15.77,781.81 -18.25,749 28.76,742.26 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-form&quot;)/div[@class=&quot;ca-form__group ca-form__group--required five-review__form-group&quot;]/div[@class=&quot;five-review__stars-rating js-review-stars&quot;]/div[@class=&quot;stars-rtg stars-rtg--md stars-rtg--empty stars-rtg--intv five-review__stars js-stars-rating&quot;]/svg[@class=&quot;js-stars-rating__star&quot;]/polygon[@class=&quot;ca-icon__colored-stroke ca-icon__colored-fill&quot;]</value>
   </webElementProperties>
</WebElementEntity>
