<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Terms_of_use_reviews</name>
   <tag></tag>
   <elementGuidId>28a8bad9-09f3-4b95-8957-4dddd9c3d973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;id-form&quot;]/div[6]/div/label</value>
   </webElementProperties>
</WebElementEntity>
