<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>what_company_are_you</name>
   <tag></tag>
   <elementGuidId>897f73c3-c28e-481b-b112-1d15b6ed4189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;id-form&quot;]/div[1]/div/div[1]/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
