<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subLabel_test</name>
   <tag></tag>
   <elementGuidId>1d8b483a-781a-4f2b-a12d-2d9752fb6fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-lbl-sbttl&quot;]/div/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-lbl-sbttl&quot;]/div/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
