<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subLabel_Important</name>
   <tag></tag>
   <elementGuidId>bfbfad5e-0bfc-449d-9a4b-b794b4204b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-lbl-sbttl&quot;]/div/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-lbl-sbttl&quot;]/div/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
