<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View_all_Categories</name>
   <tag></tag>
   <elementGuidId>973d00e3-fd2d-40ac-9c33-eec8d6b902bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrpr&quot;]/main/section[4]/div[2]/div/div[6]/div/a</value>
   </webElementProperties>
</WebElementEntity>
